// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NorthWindEF2.Models;

public partial class Utenti
{
    public Guid Guid { get; set; }

    public string Nome { get; set; }

    public string Cognome { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public DateTime? DataUltimoAccesso { get; set; }

    public string Note { get; set; }
}