// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class AnagraficheGestori
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Cognome { get; set; }

    public DateTime DataNascita { get; set; }

    public int IdUtenza { get; set; }

    public DateTime DataCreazione { get; set; }

    public DateTime DataAggiornamento { get; set; }

    public string Cap { get; set; }

    public string Citta { get; set; }

    public string Indirizzo { get; set; }

    public string Telefono { get; set; }

    public bool Abilitato { get; set; }

    public DateTime? DataCancellazione { get; set; }

    public string CodiceFiscale { get; set; }

    public virtual Utenze IdUtenzaNavigation { get; set; }
}