// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class AnagraficheGestori:BaseEntity
{

    public string Nome { get; set; }

    public string Cognome { get; set; }

    public DateTime DataNascita { get; set; }

    public int IdUtenza { get; set; }



    public string Cap { get; set; }

    public string Citta { get; set; }

    public string Indirizzo { get; set; }

    public string Telefono { get; set; }



    public string CodiceFiscale { get; set; }

    public virtual Utenze IdUtenzaNavigation { get; set; }
}