// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class Appuntamento
{
    public int Id { get; set; }

    public int IdCliente { get; set; }

    public int IdDisponibilitaMedico { get; set; }

    public DateTime Inizio { get; set; }

    public DateTime Fine { get; set; }

    public bool Disdetto { get; set; }

    public string Note { get; set; }

    public string LinkZoom { get; set; }

    public bool VisitaEffetturata { get; set; }

    public int IdUtenzaCreazione { get; set; }

    public DateTime DataCreazione { get; set; }

    public DateTime? DataAggiornamento { get; set; }

    public bool Abilitato { get; set; }

    public DateTime? DataCancellazione { get; set; }

    public DateTime? DataInizioCliente { get; set; }

    public DateTime? DataFineCliente { get; set; }

    public DateTime? DataInizioMedico { get; set; }

    public DateTime? DataFineMedico { get; set; }

    public int IdPrestazione { get; set; }

    public int Stato { get; set; }
}