// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class Audit
{
    public int Id { get; set; }

    public int IdUtenza { get; set; }

    public string Azione { get; set; }

    public string UserAgent { get; set; }

    public string Ip { get; set; }

    public string InfoAddizionali { get; set; }

    public DateTime DataCreazione { get; set; }

    public DateTime DataAggiornamento { get; set; }

    public bool Abilitato { get; set; }

    public DateTime? DataCancellazione { get; set; }
}