// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class Capcomuni
{
    public int Id { get; set; }

    public string Comune { get; set; }

    public string Cap { get; set; }

    public string Provincia { get; set; }

    public string Regione { get; set; }
}