// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class ClientiPacchetti
{
    public int Id { get; set; }

    public Guid GuidCp { get; set; }

    public Guid GuidPacchetto { get; set; }

    public int IdPacchetto { get; set; }

    public int IdCliente { get; set; }

    public string StatoPagamento { get; set; }

    public DateTime DataScadenza { get; set; }

    public DateTime DataCreazione { get; set; }

    public DateTime? DataAggiornamento { get; set; }

    public bool Abilitato { get; set; }

    public DateTime? DataCancellazione { get; set; }

    public bool Pagato { get; set; }

    public string DatiClientePacchetto { get; set; }
}