// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class CompensiPrestazioni
{
    public int Id { get; set; }

    public int IdMedico { get; set; }

    public int IdPrestazione { get; set; }

    public int Percentuale { get; set; }
}