// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class Fatture
{
    public int Id { get; set; }

    public Guid GuidCp { get; set; }

    public string NumeroFattura { get; set; }

    public DateTime DataEmissione { get; set; }

    public string RagioneSociale { get; set; }

    public string Indirizzo { get; set; }

    public string Cap { get; set; }

    public string Citta { get; set; }

    public string CodiceFiscalePiva { get; set; }

    public string CodiceDestinatarioSdi { get; set; }

    public DateTime DataCreazione { get; set; }

    public DateTime? DataAggiornamento { get; set; }

    public bool Abilitato { get; set; }

    public DateTime? DataCancellazione { get; set; }

    public string Provincia { get; set; }
}