// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class Geoitalium
{
    public string CodiceRegione { get; set; }

    public string CodiceDellUnitàTerritorialeSovracomunaleValidaAFiniSta { get; set; }

    public string CodiceProvinciaStorico1 { get; set; }

    public string ProgressivoDelComune2 { get; set; }

    public string CodiceComuneFormatoAlfanumerico { get; set; }

    public string DenominazioneItalianaEStraniera { get; set; }

    public string DenominazioneInItaliano { get; set; }

    public string DenominazioneAltraLingua { get; set; }

    public double? CodiceRipartizioneGeografica { get; set; }

    public string RipartizioneGeografica { get; set; }

    public string DenominazioneRegione { get; set; }

    public string DenominazioneDellUnitàTerritorialeSovracomunaleValidaAF { get; set; }

    public double? TipologiaDiUnitàTerritorialeSovracomunale { get; set; }

    public double? FlagComuneCapoluogoDiProvinciaCittàMetropolitanaLiberoCo { get; set; }

    public string SiglaAutomobilistica { get; set; }

    public double? CodiceComuneFormatoNumerico { get; set; }

    public double? CodiceComuneNumericoCon110ProvinceDal2010Al2016 { get; set; }

    public double? CodiceComuneNumericoCon107ProvinceDal2006Al2009 { get; set; }

    public double? CodiceComuneNumericoCon103ProvinceDal1995Al2005 { get; set; }

    public string CodiceCatastaleDelComune { get; set; }

    public string CodiceNuts12010 { get; set; }

    public string CodiceNuts220103 { get; set; }

    public string CodiceNuts32010 { get; set; }

    public string CodiceNuts12021 { get; set; }

    public string CodiceNuts220213 { get; set; }

    public string CodiceNuts32021 { get; set; }
}