// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class LogMail
{
    public int Id { get; set; }

    public string Vista { get; set; }

    public string IdEmail { get; set; }

    public string Nome { get; set; }

    public string Cognome { get; set; }

    public string Body { get; set; }

    public string Subject { get; set; }

    public string Email { get; set; }

    public DateTime? DataInvio { get; set; }

    public string Errore { get; set; }
}