// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class Messaggi
{
    public int Id { get; set; }

    public string Testo { get; set; }

    public int IdMedico { get; set; }

    public int IdCliente { get; set; }

    public DateTime DataInvio { get; set; }

    public bool IsCliente { get; set; }

    public DateTime DataCreazione { get; set; }

    public DateTime? DataAggiornamento { get; set; }

    public bool Abilitato { get; set; }

    public DateTime? DataCancellazione { get; set; }

    public string Allegato { get; set; }
}