// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class Pacchetti
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public decimal Prezzo { get; set; }

    public int DurataMesi { get; set; }

    public string Dettaglio { get; set; }

    public bool IsStart { get; set; }

    public DateTime DataCreazione { get; set; }

    public DateTime? DataAggiornamento { get; set; }

    public bool Abilitato { get; set; }

    public DateTime? DataCancellazione { get; set; }

    public Guid GuidPacchetto { get; set; }

    public string Coupon { get; set; }
}