// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class Pagamento
{
    public int Id { get; set; }

    public DateTime DataCreazione { get; set; }

    public DateTime DataAggiornamento { get; set; }

    public bool Abilitato { get; set; }

    public DateTime? DataCancellazione { get; set; }

    public string CodTrans { get; set; }

    public int? EsitoNexi { get; set; }

    public string EsitoDaNexi { get; set; }

    public Guid GuidPacchetto { get; set; }

    public string Coupon { get; set; }
}