// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class StatistichePesoClienti
{
    public int IdCliente { get; set; }

    public double Peso { get; set; }

    public DateTime DataInserimento { get; set; }

    public virtual AnagraficheClienti IdClienteNavigation { get; set; }
}