// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCCM.Models;

public partial class TemplateMail
{
    public int Id { get; set; }

    public string NomeTemplate { get; set; }

    public string Template { get; set; }
}