// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NorthWindEF.Models;

public partial class Sessioni
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public DateTime DataInizio { get; set; }

    public DateTime? DataFine { get; set; }
}